language: python
cache: pip
matrix:
    include:
      - python: 3.5
        env: TEST_TYPE="pytest"
      - python: 3.6
        env: TEST_TYPE="pytest"
      - python: 3.7
        env: TEST_TYPE="pytest" PYPI_DEPLOY=true
      - python: 3.7
        env: TEST_TYPE="pre-commit"
install:
  - pip install --upgrade pip wheel setuptools
  - |
      if [[ "$TEST_TYPE" == "pre-commit" ]]; then
        pip install -e .[code_style]
      fi
  - |
      if [[ "$TEST_TYPE" == "pytest" ]]; then
        pip install -e .[testing,sphinx]
        pip install coveralls
      fi
before_script:
    - (cd tests/test_commonmark && ./spec.sh)
script:
- |
  if [[ "$TEST_TYPE" == "pytest" ]]; then
      pytest -v --cov=myst_parser --cov-report=
  fi
- |
  if [[ "$TEST_TYPE" == "pre-commit" ]]; then
    pre-commit run --all-files || ( git status --short ; git diff ; exit 1 )
  fi
after_success:
- |
  if [[ "$TEST_TYPE" == "pytest" ]]; then
      coveralls
  fi

deploy:
  - provider: pypi
    distributions: "sdist bdist_wheel"
    user: cjsewell
    password:
      secure: XDaPRuCORFOvwXUfP6S5QOsFOpQmQiURGA603Rs3WkY0Y4up1uQjDWu2wUCh4cNPM5ITMXMFrRCWCFh289LM21c5pzExvx7RpsXfHol6F0hMGxjwmeU2aRltaVCa/zvevdBmgTa0aOMhOGmiLnSHxSAXYUHxkkHG4GmypsAshWNzJGSzSPBwt6YBkqXkeeJYC0S+t8tFEDjtEwn6E3Iy49L25+mI5ip8N6JRgAgR6umTCfKcCMBuyBii+/VDGKGsM4bdiDnXiDYWn0l9hzzSMr1xeiYtXB56N+6eRgm2oprRNnX4widbq3UJ5tp5/p3R7xXBi7NTz82d2vncNjk9Q3y35AyNb08Y2jJSsAw5CcWjQITvxMsHjhLibvrn/skkLgtE005ItNn4IFceH/y6HgmBn1yrA2z9bxfB5VLmsl4UqXYvn7Bd0l8C4IIbhsxtvH/yOtJ0sXQI3HTZVepJcrf8mAGfJVdnd9eqtMfXIr+6vlRqJByMK8f7drpdfWynC8bzfFrNIh/OHKoZzvEk7o6cDCj91vPcpxygecHvPDf0Tx/vdOFwEF8LTXNWVPjTHJMzurw946vpArCoAC1T8uwF+5fiu/ZcEfudKKincS6K9/2aFzgpoKOdbKP9/1h3hRjjPKc8HqTt9jziwuOl//KS0DJS3BSZZvFyaBI2p/Y=
    on:
      branch: master
      tags: true
      condition: $PYPI_DEPLOY = true
