language: python
cache: pip
matrix:
    include:
      - python: 3.5
        env: TEST_TYPE="pytest"
      - python: 3.6
        env: TEST_TYPE="pytest"
      - python: 3.7
        env: TEST_TYPE="pytest"
      - python: 3.7
        env: TEST_TYPE="pre-commit"
install:
  - pip install --upgrade pip wheel setuptools
  - |
      if [[ "$TEST_TYPE" == "pre-commit" ]]; then
        pip install -e .[code_style]
      fi
  - |
      if [[ "$TEST_TYPE" == "pytest" ]]; then
        pip install -e .[testing,sphinx]
        pip install coveralls
      fi
before_script:
    - (cd tests/commonmark && ./spec.sh)
script:
- |
  if [[ "$TEST_TYPE" == "pytest" ]]; then
      pytest -v --cov=myst_parser --cov-report=
  fi
- |
  if [[ "$TEST_TYPE" == "pre-commit" ]]; then
    pre-commit run --all-files || ( git status --short ; git diff ; exit 1 )
  fi
after_success:
- |
  if [[ "$TEST_TYPE" == "pytest" ]]; then
      coveralls
  fi
